export const FETCH_ALBUM_REQUEST = "FETCH_ALBUM_REQUEST";
export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const FETCH_ALBUM_FAILURE = "FETCH_ALBUM_FAILURE";

export const CREATE_ALBUM_REQUEST = "CREATE_ALBUM_REQUEST";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAILURE = "CREATE_ALBUM_FAILURE";

export const UPDATE_ALBUM_REQUEST = "UPDATE_ALBUM_REQUEST";
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS";
export const UPDATE_ALBUM_FAILURE = "UPDATE_ALBUM_FAILURE";

export const DELETE_ALBUM_REQUEST = "DELETE_ALBUM_REQUEST";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAILURE = "DELETE_ALBUM_FAILURE";